version: "3.9"

services:
  proxy:
    container_name: proxy
    image: mikki028/proxy
    ports:
      - "2000:2000/udp"
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

  pickle:
    container_name: pickle
    image: mikki028/pickle
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

  xml:
    container_name: xml
    image: mikki028/xml
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

  json:
    container_name: json
    image: mikki028/json
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

  protobuf:
    container_name: protobuf
    image: mikki028/protobuf
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

  avro:
    container_name: avro
    image: mikki028/avro
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

  yaml:
    container_name: yaml
    image: mikki028/yaml
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

  message_pack:
    container_name: message_pack
    image: mikki028/message_pack
    networks:
      - soa
    environment:
      - MULTICAST_GROUP

networks:
  soa:
